#!/bin/sh
################################################
# build login.cgi using build_cgi
#
# author:  mgill 
# created: Sun Feb 11 23:30:07 EST 2018
################################################
#
build_cgi login.cgi login.cpp
