#!/bin/sh
################################################
# build index.cgi using build_cgi
#
# author:  mgill 
# created: Sun Feb 11 22:22:36 EST 2018
################################################
#
build_cgi index.cgi index.cpp
